language: rust
os:
- linux
- osx
rust:
- nightly
- stable
matrix:
  allow_failures:
  - os: linux
    rust: nightly
  - os: osx
    rust: nightly
before_install:
- chmod +x .travis/*.sh
- 'if [[ -f ".travis/${TRAVIS_OS_NAME}_before_install.sh" ]]; then .travis/${TRAVIS_OS_NAME}_before_install.sh; fi'
install:
- 'if [[ -f ".travis/${TRAVIS_OS_NAME}_install.sh" ]]; then .travis/${TRAVIS_OS_NAME}_install.sh; fi'
script:
- 'if [[ -f ".travis/${TRAVIS_OS_NAME}_script.sh" ]]; then .travis/${TRAVIS_OS_NAME}_script.sh; fi'
- export DEFAULT_TARGET=$(rustup show | grep default | grep -Po "^[^-]+-\K\S+")
- pushd tcod_sys; cargo build --features generate_bindings; popd
- 'export BINDINGS_FILE=${DEFAULT_TARGET}_bindings.rs; echo "$BINDINGS_FILE download:"'
- curl -F "file=@./tcod_sys/${BINDINGS_FILE}" https://file.io/ | grep -Po '"link":"\K[^"]+'
- cargo build --verbose
- cargo test --verbose
- cargo test --features "rustc-serialize serde" --verbose
- cargo test --release
after_success: ! '[ $TRAVIS_BRANCH = master ] &&

  [ "$TRAVIS_OS_NAME" = linux ] &&

  [ $TRAVIS_PULL_REQUEST = false ] &&

  cargo doc &&

  echo ''<meta http-equiv=refresh content="0;url=tcod/index.html">'' > target/doc/index.html
  &&

  git config --global user.email "travis@travis-ci.org" &&

  git config --global user.name "travis-ci" &&

  sudo pip install ghp-import &&

  ghp-import -n target/doc &&

  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

'
env:
  global:
  - secure: h21kqC5s6iVs4p5n9KFZ5ZTWtPF8nGVFpaPP6t/1Sg+xMaHMDyr/sBYI1gsNGTXrVsiP2Zs6cRTBEbX12PVL6MXFgKpdhKG1+lBCMk6HxU8/W2UHCh6Y38+W4Ybyv5fuoWqkUOX3yODNkRZWrqNhdm8lCdE2uGczkIKPi7hDYMM=
