[package]
name = "tcod"
version = "0.3.0"
authors = ["tomas@sedovic.cz", "arcnorj@gmail.com"]
build = "./build.sh"

[lib]

name = "tcod"
path = "src/lib.rs"


# TODO: temporarily disabling debuginfo until this is fixed:
# https://github.com/rust-lang/rust/issues/17257
[profile.dev]
debug = false
[profile.test]
debug = false
